### ISSUE TITLE
release et packaging

### ISSUE THREAD

**Issue by boly38** [boly38/pocgdx#8]
Faire en sorte que les packagings produits apparaissent comme livrable du dépot github lors de release

chatGPT:

----

Pour inclure les packages générés dans les livrables de votre dépôt GitHub, vous pouvez utiliser l'action GitHub Actions appelée "Upload Release Asset". Voici comment vous pouvez l'intégrer à votre workflow existant :

Tout d'abord, ajoutez les étapes supplémentaires suivantes à votre workflow :

````yaml
- name: Create Release
  id: create_release
  uses: actions/create-release@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    tag_name: ${{ github.ref }}
    release_name: Release ${{ github.ref }}
    draft: false
    prerelease: false

- name: Upload Desktop application
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: desktop/build/libs/*.jar
    asset_name: Desktop.jar
    asset_content_type: application/java-archive

- name: Upload Android application
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: android/build/outputs/apk/release/*.apk
    asset_name: Android.apk
    asset_content_type: application/vnd.android.package-archive

- name: Upload HTML application
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: html/build/dist/*
    asset_name: HTML.zip
    asset_content_type: application/zip

- name: Upload iOS application
  uses: actions/upload-release-asset@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: ios/build/robovm/*.ipa
    asset_name: iOS.ipa
    asset_content_type: application/octet-stream
````

Modifiez l'étape "Upload artifacts" existante pour supprimer les artefacts, car ils ne seront plus nécessaires :

````yaml
- name: Upload artifacts
  uses: actions/upload-artifact@v2
  with:
    name: Application Artifacts
    path: '' # Supprimez cette ligne pour ignorer l'upload des artefacts
```` 

Pour que l'action puisse accéder au jeton d'accès GitHub, assurez-vous que votre workflow s'exécute avec les autorisations appropriées. Vous pouvez utiliser la variable `secrets.GITHUB_TOKEN` pour cela.
Avec ces modifications, chaque fois que vous exécutez le workflow, il créera une nouvelle version de la release (basée sur la branche ou le tag actuel) et téléchargera les packages générés pour chaque plateforme comme des actifs de la release. Ces packages apparaîtront alors dans la section "Releases" de votre dépôt GitHub.
